version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta Management Console di RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Porta MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongo_data:/data/db

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - '9091:9091' # Porta per l'applicazione Flask
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: test_queue
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      MONGO_URI: mongodb://admin:adminpass@mongodb:27017

  consumer:
    build:
      context: ./consumer-summarize
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: test_queue
      MONGO_URI: mongodb://admin:adminpass@mongodb:27017

  extract_text_service:
    build:
      context: ./extract_text_service
      dockerfile: Dockerfile
    container_name: extract_text_service
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"   

  client_test:
    build:
      context: ./client_test
      dockerfile: Dockerfile
    container_name: client_Test
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"   

volumes:
  rabbitmq_data:
  mongo_data:
