version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta Management Console di RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Porta MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongo_data:/data/db

  producer: # SOLAMENTE PER TESTARE IL CONSUMER SUMMARIZER
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - '9091:9091' 
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: summarize_queue
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      MONGO_URI: mongodb://admin:adminpass@mongodb:27017

  consumersummarize: #Consumer summarizer 
    build:
      context: ./consumer-summarize
      dockerfile: Dockerfile
    container_name: consumersummarize
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: summarize_queue
      MONGO_URI: mongodb://admin:adminpass@mongodb:27017

  consumernlp: #Consumer summarizer 
    build:
      context: ./consumer-nlp
      dockerfile: Dockerfile
    container_name: consumernlp
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: nlp_queue
      MONGO_URI: mongodb://admin:adminpass@mongodb:27017
  consumerimagecontext: #Consumer summarizer 
    build:
      context: ./consumer-imagecontext
      dockerfile: Dockerfile
    container_name: consumerimagecontext
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: context_queue

  extract_text_service:
    build:
      context: ./extract_text_service
      dockerfile: Dockerfile
    container_name: extract_text_service
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"   

  server_centrale_springboot: #Consumer summarizer 
    build:
      context: ./server_centrale_springboot
      dockerfile: Dockerfile
    container_name: server_centrale_springboot
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      # Spring Boot Config
      - SPRING_APPLICATION_NAME=servercentrale
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

      # MongoDB Config
      - SPRING_DATA_MONGODB_URI=mongodb://admin:adminpass@mongodb:27017/server_db?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=server_db

      # Configurazione API di estrazione testo
      - EXTRACT_TEXT_API=http://extract_text_service:5001/extract/text

      # Configurazione RabbitMQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=pass
      - RABBITMQ_QUEUE_NLP=nlp_queue
      - RABBITMQ_QUEUE_SUMMARIZE=summarize_queue
      - RABBITMQ_QUEUE_CONTEXT=context_queue
    ports:
      - "8080:8080"  
  client_test:
    build:
      context: ./client_test
      dockerfile: Dockerfile
    container_name: client_Test
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"   

volumes:
  rabbitmq_data:
  mongo_data:
